#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForoULAtina.AccesoDatos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="proyecto_progra_v")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::ForoULAtina.Properties.Settings.Default.proyecto_progra_vConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insertar_usuario")]
		public int insertar_usuario([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Name", DbType="VarChar(255)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Number", DbType="VarChar(255)")] string number, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="VarChar(255)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Password", DbType="VarChar(255)")] string password, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TypeU", DbType="Char(1)")] System.Nullable<char> typeU, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Status", DbType="Bit")] System.Nullable<bool> status, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUser", DbType="Int")] ref System.Nullable<int> idUser, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> errorIdDB, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ErrorFromDB", DbType="VarChar(255)")] ref string errorFromDB)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), name, number, email, password, typeU, status, idUser, errorIdDB, errorFromDB);
			idUser = ((System.Nullable<int>)(result.GetParameterValue(6)));
			errorIdDB = ((System.Nullable<int>)(result.GetParameterValue(7)));
			errorFromDB = ((string)(result.GetParameterValue(8)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.login")]
		public int login([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Number", DbType="NVarChar(50)")] string number, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Password", DbType="NVarChar(50)")] string password, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Name", DbType="NVarChar(255)")] ref string name, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Status", DbType="Bit")] ref System.Nullable<bool> status, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TypeU", DbType="Char(1)")] ref System.Nullable<char> typeU, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> errorIdDB, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ErrorFromDB", DbType="VarChar(255)")] ref string errorFromDB)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), number, password, name, status, typeU, errorIdDB, errorFromDB);
			name = ((string)(result.GetParameterValue(2)));
			status = ((System.Nullable<bool>)(result.GetParameterValue(3)));
			typeU = ((System.Nullable<char>)(result.GetParameterValue(4)));
			errorIdDB = ((System.Nullable<int>)(result.GetParameterValue(5)));
			errorFromDB = ((string)(result.GetParameterValue(6)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.order_validate_product")]
		public int order_validate_product([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdProducto", DbType="Int")] System.Nullable<int> idProducto, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cantidad", DbType="Int")] System.Nullable<int> cantidad, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Existe", DbType="Bit")] ref System.Nullable<bool> existe, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> errorIdDB, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,0)")] ref System.Nullable<decimal> precio, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ErrorFromDB", DbType="VarChar(255)")] ref string errorFromDB)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idProducto, cantidad, existe, errorIdDB, precio, errorFromDB);
			existe = ((System.Nullable<bool>)(result.GetParameterValue(2)));
			errorIdDB = ((System.Nullable<int>)(result.GetParameterValue(3)));
			precio = ((System.Nullable<decimal>)(result.GetParameterValue(4)));
			errorFromDB = ((string)(result.GetParameterValue(5)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.actualizar_inventario")]
		public int actualizar_inventario([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> cantidadProductos, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdProducto", DbType="Int")] System.Nullable<int> idProducto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> errorIdDB, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ErrorFromDB", DbType="VarChar(255)")] ref string errorFromDB)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cantidadProductos, idProducto, errorIdDB, errorFromDB);
			errorIdDB = ((System.Nullable<int>)(result.GetParameterValue(2)));
			errorFromDB = ((string)(result.GetParameterValue(3)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.actualizar_tarjeta")]
		public int actualizar_tarjeta([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] string numero, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(4)")] string code, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> expiration, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,2)")] System.Nullable<decimal> totalComprar, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> errorIdDB, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ErrorFromDB", DbType="VarChar(255)")] ref string errorFromDB)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), numero, code, expiration, totalComprar, errorIdDB, errorFromDB);
			errorIdDB = ((System.Nullable<int>)(result.GetParameterValue(4)));
			errorFromDB = ((string)(result.GetParameterValue(5)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.crear_orden")]
		public int crear_orden([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string numeroCliente, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdProducto", DbType="VarChar(50)")] string idProducto, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cantidad", DbType="VarChar(50)")] string cantidad, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] string coordenadas, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> totalComprar, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Activa", DbType="Bit")] System.Nullable<bool> activa, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> idOrden, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> errorIdDB, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ErrorFromDB", DbType="VarChar(255)")] ref string errorFromDB)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), numeroCliente, idProducto, cantidad, coordenadas, totalComprar, activa, idOrden, errorIdDB, errorFromDB);
			idOrden = ((System.Nullable<int>)(result.GetParameterValue(6)));
			errorIdDB = ((System.Nullable<int>)(result.GetParameterValue(7)));
			errorFromDB = ((string)(result.GetParameterValue(8)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.order_validate_number")]
		public ISingleResult<order_validate_numberResult> order_validate_number([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Number", DbType="VarChar(255)")] string number, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> errorIdDB, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ErrorFromDB", DbType="VarChar(255)")] ref string errorFromDB)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), number, errorIdDB, errorFromDB);
			errorIdDB = ((System.Nullable<int>)(result.GetParameterValue(1)));
			errorFromDB = ((string)(result.GetParameterValue(2)));
			return ((ISingleResult<order_validate_numberResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.order_validate_compra")]
		public int order_validate_compra([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] string numero, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(4)")] string code, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> expiration, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,2)")] System.Nullable<decimal> totalComprar, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ValidarCompra", DbType="Bit")] ref System.Nullable<bool> validarCompra, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> errorIdDB, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ErrorFromDB", DbType="VarChar(255)")] ref string errorFromDB)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), numero, code, expiration, totalComprar, validarCompra, errorIdDB, errorFromDB);
			validarCompra = ((System.Nullable<bool>)(result.GetParameterValue(4)));
			errorIdDB = ((System.Nullable<int>)(result.GetParameterValue(5)));
			errorFromDB = ((string)(result.GetParameterValue(6)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.retornar_productos_disponibles")]
		public ISingleResult<retornar_productos_disponiblesResult> retornar_productos_disponibles([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> errorIdDB, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ErrorFromDB", DbType="VarChar(255)")] ref string errorFromDB)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), errorIdDB, errorFromDB);
			errorIdDB = ((System.Nullable<int>)(result.GetParameterValue(0)));
			errorFromDB = ((string)(result.GetParameterValue(1)));
			return ((ISingleResult<retornar_productos_disponiblesResult>)(result.ReturnValue));
		}
	}
	
	public partial class order_validate_numberResult
	{
		
		private int _Id;
		
		private string _Name;
		
		private string _Number;
		
		private string _Email;
		
		private string _Password;
		
		private char _TypeU;
		
		private bool _Status;
		
		public order_validate_numberResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Number", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string Number
		{
			get
			{
				return this._Number;
			}
			set
			{
				if ((this._Number != value))
				{
					this._Number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(255)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this._Password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypeU", DbType="Char(1) NOT NULL")]
		public char TypeU
		{
			get
			{
				return this._TypeU;
			}
			set
			{
				if ((this._TypeU != value))
				{
					this._TypeU = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Bit NOT NULL")]
		public bool Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
	}
	
	public partial class retornar_productos_disponiblesResult
	{
		
		private int _idProducto;
		
		private string _Name;
		
		private int _Cantidad;
		
		private decimal _Precio;
		
		public retornar_productos_disponiblesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idProducto", DbType="Int NOT NULL")]
		public int idProducto
		{
			get
			{
				return this._idProducto;
			}
			set
			{
				if ((this._idProducto != value))
				{
					this._idProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cantidad", DbType="Int NOT NULL")]
		public int Cantidad
		{
			get
			{
				return this._Cantidad;
			}
			set
			{
				if ((this._Cantidad != value))
				{
					this._Cantidad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Precio", DbType="Decimal(6,3) NOT NULL")]
		public decimal Precio
		{
			get
			{
				return this._Precio;
			}
			set
			{
				if ((this._Precio != value))
				{
					this._Precio = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
